apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.redis.appName }}
  ports:
    - protocol: TCP
      port: 6380	
      targetPort: 6380
