apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ngnix.primaryDeployment }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ngnix.primaryreplicaSet }}
  selector:
    matchLabels:
      app: {{ .Values.ngnix.primaryApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.ngnix.primaryApp }}
    spec:
      containers:
        - name: {{ .Values.ngnix.primaryApp }}
          image: {{ .Values.ngnix.imageName }}:green
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ngnix.canaryDeployment }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ngnix.canaryreplicaSet }}
  selector:
    matchLabels:
      app: {{ .Values.ngnix.canaryApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.ngnix.canaryApp }}
    spec:
      containers:
        - name: {{ .Values.ngnix.canaryApp }}
          image: {{ .Values.ngnix.imageName }}:blue
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ngnix.ingressController }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.ngnix.ingressName }}
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 2   
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.ngnix.ingressName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.ngnix.ingressName }}
    spec:
      containers:
      - name: nginx-ingress-controller
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0
        args:
        - /nginx-ingress-controller
        - --publish-service={{ .Values.namespace }}/nginx-ingress-controller-set1
        - --configmap={{ .Values.namespace }}/nginx-ingress-controller-set1
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
